[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_spl_staking = "2RLGCgJVFCc7frbJJBFRxsXuJ3rsUKoKCg5XQ6SLzvR9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sarmat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
